# -*- coding: utf-8 -*-
"""Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18C4NW8WXuJ-u6bLVpsqW0DlTA8IPZ39V

### **Project Title :-** **Hotel Booking Data Analysis**
**By :-** Jayant Bhoyar

**Project Type :-** Exploratory Data Analysis (EDA)

### **Project Summary :-**
This project focuses on a comprehensive data analysis of hotel bookings to uncover meaningful insights related to guest behavior and hotel performance. The dataset is divided into two categories: City Hotel and Resort Hotel, allowing for comparative analysis across different hotel types.
Before performing any visualizations, the data undergoes thorough data cleaning. This includes handling null values, removing duplicate records, and ensuring consistency across all columns. These steps are crucial to ensure accurate and reliable analysis.

The objective of the project is to provide actionable insights that hotel managers can use to improve guest satisfaction, optimize room allocation, and reduce cancellations through data-driven decision-making.

### **Problem Statement**
This dataset contains booking information for a City Hotel and a Resort Hotel, including details such as the date of booking, number of adults and children, length of stay, available parking spaces, meal preferences, booking channel, and the agent responsible for the booking.

The objective of this project is to explore and analyze the dataset to uncover important factors that influence hotel bookings and cancellations. By examining various guest attributes and booking details, the analysis aims to provide insights into customer behavior, seasonality, cancellation trends, and preferences, which can help hotel management make data-driven decisions to enhance guest satisfaction and optimize operations.

###**Define Your Business Objective ?**
Analyse and visualize the data on bookings of City Hotel and Resort Hotel to gain insights on the different factors that affect the booking and ADR.

### **General Guidelines :-**
**1.Write clean and clear code.**

*   Add comments for every step.
*   Organize your code properly.

**2.For every chart, answer these 3 points:**

*   Why did you use this type of chart?
*   What are the insights found from the chart?
*   Can this help improve the business? How?

**3.Use different types of charts.**
*   Bar, line, pie, heatmap, scatter, etc.


**4.Make at least 20 charts.**

*  Each one should give a useful and new insight.

**5.Focus on business value.**

* Show how the insights can help increase sales, reduce costs, or improve service.

**6.Make a clean report.**

*   Include a summary and your final suggestions.

###***Let's Begin !***

###***1.Know Your Data***

###Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""###Dataset Loading"""

#asigned simpal name to dataset as df
df = pd.read_csv("/content/Hotel Bookings (2).csv")

"""###Dataset First View"""

#Dataset First Look
df.head()

"""###Dataset Rows And Columns Count"""

#Dataset Rows And Columns Count
df.index

#To checkthe columns in data set
list(df.columns)

"""### Dataset Information"""

df.info()

"""### Duplicate And Unique Values"""

# Count the Number Of Duplicate and unique values
duplicate_values = df.duplicated().value_counts()
unique_count = len(df) - duplicate_values

# Pie chart for visualizing duplicate vs unique
plt.figure(figsize=(6,6))
duplicate_values,unique_count.plot(kind="pie",shadow = True ,labels=["Duplicates", "Unique"],autopct="%1.1f%%",colors=['lightcoral','skyblue'])
plt.title("Duplicate vs Unique Rows")
plt.ylabel(" ")
plt.show()

# Datase Duplicate Value Drop
df.drop_duplicates(inplace=True)

# Reset The Index To View The Unique Data
df.reset_index(drop=True, inplace=True)

"""### Missing Values/Null Values"""

#missing Values/Null Values Count
null_values = df.isna()==True
null_values

#We Have Replaced All Null Values as NaN
df.fillna(np.nan,inplace=True)
df

# Count the missing values
a=df.isna().sum()
missing_values=a.sort_values(ascending=False)[:5]
missing_values

#Visualize the missing values
plt.figure(figsize=(8,4))
missing_values.plot(kind="bar", color="skyblue")
plt.title("Visualisation of Missing Values")
plt.ylabel("Number of Missing Values")
plt.xticks(rotation=25)
plt.show()

"""###What did you know about your dataset?

1.The dataset provided contains detailed records of hotel bookings. Our task is to analyze and explore this data to uncover key insights and identify the main factors that influence booking behaviors — including cancellations, guest preferences, and booking patterns.
It consists of 119,390 rows and 32 columns, each representing a specific feature related to hotel reservations.


2.Upon initial inspection, we found 31,994 duplicate rows in the dataset. These rows were removed to maintain data accuracy and eliminate redundancy during analysis.

3.There are 4 Columns in Dataset which is having missing values and those columns are company,agent,country and children.

4.There are separate columns called adults,children and babies that show the total number of people who are coming to visit, so instead of different columns will add these three in one called total_num_people

###**2.Understanding Your Variables**
"""

#Dataset Columns
list(df.columns)

#Dataset Discribe
df.describe(include="all")

"""###Variables Description

*  hotel – Type of hotel (e.g., Resort Hotel, City Hotel).

*   is_canceled – Whether the booking was canceled (0 = No, 1 = Yes).

*   lead_time – Number of days between booking and arrival.

*  arrival_date_year – Year of arrival (e.g., 2015, 2016, 2017).


*  arrival_date_month – Month of arrival (e.g., July, August).

*   arrival_date_week_number – Week number of the year.

*   arrival_date_day_of_month – Day of the month the guest arrived (1–31).

*   stays_in_weekend_nights – Number of weekend nights stayed (Saturday or Sunday).


* stays_in_week_nights – Number of weekday nights stayed (Monday to Friday).
*  adults – Number of adults.

*  children – Number of children.


*  babies – Number of babies.

* meal – Type of meal booked (e.g., BB = Bed & Breakfast, FB = Full Board, HB = Half Board).

* country – Country of origin (e.g., PRT = Portugal, GBR = Great Britain).
*  market_segment – How the booking was made (e.g., Direct, Online TA = Online Travel Agent).

* distribution_channel – Channel used for distribution (e.g., Direct, TA/TO = Travel Agent/Tour Operator).


* is_repeated_guest – Whether the guest has stayed at the hotel before (0 = No, 1 = Yes).


* previous_cancellations – Number of previous bookings canceled by the customer.



*  previous_bookings_not_canceled – Number of previous bookings not canceled.


* previous_bookings_not_canceled – Number of previous bookings not canceled.


*  reserved_room_type – Room type reserved by the customer.

* assigned_room_type – Room type actually assigned to the customer.
*   booking_changes – Number of changes made to the booking.



* deposit_type – Type of deposit (e.g., No Deposit, Refundable, Non Refund).


*  agent – ID of the travel agency that made the booking.


* company – ID of the company that made the booking (if applicable).

* days_in_waiting_list – Number of days the booking was on the waiting list.

*  customer_type – Type of customer (e.g., Transient, Contract, Group).


*  adr – Average Daily Rate (revenue per occupied room).
*  required_car_parking_spaces – Number of parking spaces required.


*  total_of_special_requests – Number of special requests made (e.g., twin beds, high floor).


* reservation_status – Final status of the reservation (e.g., Check-Out, Canceled, No-Show).


* reservation_status_date – Date when the reservation status was set.

###Check Unique Values for each variable
"""

# Check Unique Values for each variable.
# we describe all the unique values using labda function of indivisual column.
a=df.apply(lambda col: col.unique())
print(a)

"""##3.Data Wrangling

### We already did some data cleaning before lets go for data wrangling

### Data Wrangling Code
"""

#Write your code to make your dataset analysis ready.
#making a copy of data set
df1=df.copy()

#Adding total staying days in hotels
df1["total_stay"]=df1["stays_in_weekend_nights"]+df1["stays_in_week_nights"]

#Adding total people num as a column.
df1["total_num_people"]=df1["adults"]+df1["children"]+df1["babies"]

df1.head()

#there are some rows with total number of adults,children or babies equal to zero this means there is no any booking were made.
#so we can remove such rows
df1[df1["total_num_people"]==0].shape

df1.drop(df1[df1["total_num_people"]==0].index, inplace=True)
df1.head()

"""###What all manipulations have you done and insights you found?

1 . Three columns 'adults' , 'children' , 'babies' had valuen zero which means no booking has done here , so those columns were removed

2 . In dataset , there were 31994 duplicate values.so those values were removed.

3 . There were 4 columns which have missing values and the columns were 'company' , 'agent' , 'country' , 'children' . the values from these columns are replaced by NaN

4 . In dataframe added two columns total_stay and total_num_people.

## **4.Data Visualization,Storytelling & Experimennting With Charts : Understand The Relationships Between Variables**

Chart 1

Question no.1. What is the cancellation rate across hotel types?
"""

# Chart 1 visualization code
cancellation_rate = df.groupby('hotel')['is_canceled'].mean()
cancellation_rate
# Bar chart for visualizing cancellation rate across hotel types

cancellation_rate.plot(kind="bar",color=['skyblue', 'salmon'])
plt.title("'Cancellation Rate by Hotel Type'")
plt.xlabel('Hotel Type')
plt.ylabel('Cancellation Rate')
plt.xticks(rotation=0)
plt.show()

"""1. Why did you pick the specific chart?

**I used the Bar Chart To Compares average cancellation rate across two hotel types.**

2.What are the insights found from the chart?

**Based on the above observations,i found that City Hotel has a noticeably higher cancellation rate than Resort Hotel.**

3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, the insight helps create a positive business impact.
City hotels can apply stricter cancellation policies or introduce prepayment options to reduce last-minute revenue loss. Resort hotels, having a lower cancellation rate, can maintain flexible policies to retain their loyal customer base. Understanding this helps both hotel types manage inventory and pricing strategies more effectively.**

Question no.2  Which months have the most hotel bookings?
"""

# Chart 2 visualization code
monthly_bookings = df["arrival_date_month"].value_counts()
ordered_months = ['January','February','March','April','May','June',
                  'July','August','September','October','November','December']
monthly_bookings = monthly_bookings.reindex(ordered_months)

monthly_bookings
# line chart for visualizing cancellation rate across hotel types
plt.figure(figsize=(10, 6))
monthly_bookings.plot(kind="line", marker='o',color='skyblue')
plt.title('Monthly Booking Volume (Line Chart)')
plt.xlabel('Month')
plt.ylabel('Number of Bookings')
plt.xticks(rotation=45)
plt.grid(linestyle='--')
plt.show()

"""1. Why did you pick the specific chart?
**I used the Line chat for visualizing trends over an ordered sequence like months.**

2.What are the insights found from the chart?

  **Based on the above observations i found that Clear peak during July and August (summer holidays).**

**Booking volume gradually declines from September to November.**

**January and December are the slowest months in terms of bookings.**

3 . Will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, this supports positive business decisions.
Hotels can increase room rates and staff during high season to maximize revenue. In low-demand months, promotions, loyalty discounts, or bundled services can help maintain occupancy. Knowing seasonality trends helps optimize operations, marketing, and staff scheduling.**

Question no 3. How many people booked each year?
"""

# Chart 3 visualization code
bookings_by_year = df['arrival_date_year'].value_counts()
bookings_by_year
# Plotting pie chart
plt.figure(figsize=(6, 6))
bookings_by_year.plot(kind="pie", shadow = True,labels=bookings_by_year.index, autopct='%1.1f%%', startangle=90, colors=['lightblue', 'lightgreen', 'salmon'])
plt.title('Bookings Distribution by Year')
plt.ylabel(" ")
plt.show()

"""1.Why did you pick the specific chart?

**I used pie chat because It shows how bookings change from one year to the next**

2.What are the insights found from the chart?

**Based on the above observations i found that 2016 and 2017 had the most bookings and 2015 had fewer bookings.**

3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, understanding yearly trends helps with long-term planning.
If a drop is observed, especially in recent years, hotels can investigate external factors (e.g., economic downturn, travel restrictions) and adjust campaigns. An upward trend provides confidence to scale operations or expand.**

Question No.4 What are the most popular meal types?
"""

# Chart 4 visualization code
Popular_meal_type = df["meal"].value_counts()
Popular_meal_type
# Plotting bar chart
plt.figure(figsize=(7,4))
Popular_meal_type.plot(kind='bar', color='seagreen')
plt.title('Meal Preferences')
plt.xlabel('Meal Type')
plt.ylabel('Number of Bookings')
plt.xticks(rotation=0)
plt.show()

"""1.Why did you pick the specific chart?

**I used bar chart because Bar charts are ideal for comparing quantities across categories.**

2.What are the insights found from the chart?

 **Based on the above observations i found that BB (Bed & Breakfast) is by far the most chosen option.**

3 . Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, definitely positive.
Hotels can upsell breakfast-inclusive deals or premium breakfast options. For customers not opting in, targeted in-stay promotions can convert them. It also helps in managing F&B operations efficiently.**

Question No. 5 - Which hotel type had more bookings?
"""

# Count number of bookings for each hotel type
hotel_counts = df['hotel'].value_counts()
# Create a pie chart
plt.figure(figsize=(6, 6))
hotel_counts.plot(kind='pie', autopct='%1.1f%%',shadow = True, colors=['skyblue', 'gold'], startangle=90)
plt.title('Percentage of Bookings by Hotel Type')
plt.ylabel('')
plt.show()

"""1.Why did you pick the specific chart?

**I used the pie chart because Simple way to compare total bookings for each hotel.**

2.What are the insights found from the chart?

**Based on the above observations i found that City Hotel had more bookings than Resort Hotel.**

3 . Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, this insight is valuable.
City hotels can introduce more value-added services to boost revenue. Resort hotels can analyze city hotel offerings and improve their facilities or promote exclusive vacation packages to attract customers. Learning from top performers helps weaker segments grow.**

Question No. 6 -What’s the most booked room type?
"""

# Count bookings per room type
room_type_counts = df['reserved_room_type'].value_counts()
room_type_counts
# Plot horizontal bar chart
plt.figure(figsize=(8, 5))
room_type_counts.plot(kind='barh', color='skyblue')
plt.xlabel('Number of Bookings')
plt.ylabel('Room Type')
plt.title('Most Booked Room Types')
plt.gca().invert_yaxis()  # Put highest on top
plt.show()

"""1.Why did you pick the specific chart?

**I used the horizontal bar chart because A horizontal bar chart is great for comparing categories with different volumes**

2.What are the insights found from the chart?

**Based on the above observations i found that Room Type A dominates the bookings.
Other room types are significantly less in demand.**

3 . Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, this leads to smarter inventory and pricing management.
Popular room types can be offered in bundles, or slightly upgraded versions can be sold at a premium. Less-booked types might be converted or redesigned. Understanding preferences helps align supply with demand.**

Question No. 7 -   Which country has the most bookings?
"""

#count country has the most booking
most_book_country = df['country'].value_counts().head(10)
# Plot bar chart
most_book_country.plot(kind='bar', color='seagreen')
plt.title('Top 10 Countries by Bookings')
plt.ylabel('Number of Bookings')
plt.xlabel('Country Code')
plt.xticks(rotation=45)
plt.show()

"""1.Why did you pick the specific chart?

**I used the bar chart because
To see where most of your guests come from, a bar chart clearly shows the top countries.**

2.What are the insights found from the chart?

**Based on the above observations i found that The majority of bookings are from Portugal (PRT)  possibly because the hotel is located there.**

3.Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, highly positive.
Targeted marketing can be run in high-performing countries. For low-performing ones, hotels can offer international deals or partner with local travel agents. Understanding guest origin helps with cultural services, payment options, and language support.**

Question No. 8 What is the average daily rate (ADR)?
"""

# Step 1: Filter to only actual stays (not canceled)
completed_bookings = df[df['is_canceled'] == 0]

# Step 2: Calculate the average daily rate (ADR) per hotel type
adr_by_hotel = completed_bookings.groupby('hotel')['adr'].mean()

# Step 3: Plot the ADRs
adr_by_hotel.plot(kind='bar', color='coral')
plt.title('Average Daily Rate (ADR) by Hotel Type')
plt.ylabel('Average Rate')
plt.xlabel('Hotel Type')
plt.xticks(rotation=0)
plt.show()

"""1.Why did you pick the specific chart?

**I used the bar chart because Simple comparison between City Hotel and Resort Hotel.**

2.What are the insights found from the chart?

**Based on the above observations i found that the City Hotels generally have higher ADR than Resort Hotels.**

3.Will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, it helps define pricing strategies.
City hotels can offer premium services to raise ADR. Resort hotels can monitor competitor rates and ensure their higher ADR is justified with experience. Balancing ADR and occupancy ensures healthy revenue per available room.**

Question No.9 What is the distribution of lead time?
"""

# Plot histogram of lead times
df['lead_time'].plot(kind='hist', bins=50, color='orchid')
plt.title('Lead Time Distribution')
plt.xlabel('Days Before Arrival')
plt.ylabel('Number of Bookings')
plt.show()

"""1.Why did you pick the specific chart?

**I used the bar chart because lead_time tells how many days in advance a booking was made.**

**Histogram is best for showing distribution of a continuous variable.**

2.What are the insights found from the chart?

**Based on the above observations i found that the Many bookings occur 30–100 days in advance .**

3.Will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.


**Yes, this improves forecast accuracy and pricing decisions.
Early bookings allow hotels to adjust dynamic pricing. Last-minute bookings may justify offering flash deals. Managing expectations across different booking windows enhances revenue and customer satisfaction.**

Question No.10 What are the most common customer types?
"""

# Count types of customers
customer_counts = df['customer_type'].value_counts()

# Plot as pie chart
customer_counts.plot(kind='pie', autopct='%1.1f%%', shadow = True,colors=['orange', 'skyblue', 'lightcoral', 'purple'])
plt.title('Customer Type Distribution')
plt.ylabel('')
plt.show()

"""1.Why did you pick the specific chart?

**I used the pie chart because Pie chart shows each group’s share of the total.**

2.What are the insights found from the chart?

**Based on the above observations i found that Transient guests (individual travelers) dominate bookings.**

**Group and corporate (contract) guests are much fewer.**

3. Will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.


**Yes, positive.
Yes, this is helpful. Hotels can focus on giving personalized offers and special packages to these travelers. It also shows that people prefer flexible and simple bookings. Group and corporate customers can still be targeted during slow seasons to keep business going.**

Question No.11 What’s the average stay length for weekends vs weekdays?
"""

# Filter out canceled bookings
stays = df[df['is_canceled'] == 0]

# Calculate average stays
weekend_avg = stays['stays_in_weekend_nights'].mean()
weekday_avg = stays['stays_in_week_nights'].mean()

# Plot a bar chart
plt.bar(['Weekend Nights', 'Week Nights'], [weekend_avg, weekday_avg], color=['orange', 'teal'])
plt.title('Average Stay Duration')
plt.ylabel('Nights')
plt.show()

"""1.Why did you pick the specific chart?

**I used the bar chart because We’re comparing two specific, numeric averages - average weekend stay vs. average weekday stay it is easy to quickly compare**

2.What are the insights found from the chart?

**Based on the above observations i found that Guests tend to stay longer during the week.**

**Weekends likely used for short trips.**

3.will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.


**Yes, this is useful. Hotels can make special weekend offers to encourage guests to stay longer. For example, giving a free night if someone stays Friday to Sunday. On weekdays, they can offer business-friendly services like meeting rooms or fast check-in to attract business travelers.**

Question No.12 Which market segment has the most cancellations?
"""

segment_cancel = df.groupby('market_segment')['is_canceled'].mean().sort_values() * 100
segment_cancel.plot(kind='bar', color='orange')
plt.title('Cancellation Rate by Market Segment')
plt.ylabel('Cancellation Rate (%)')
plt.xticks(rotation=45)
plt.show()

"""1.Why did you pick the specific chart?

**I used the bar chart because Each market segment (e.g., Direct, Corporate, Online TA) is a category — bar charts are perfect for comparing across categories.**

2.What are the insights found from the chart?

**Based on the above observations i found that
Online Travel Agents (OTA) show higher cancellation tendencies.**

3.will the gained insights help creating a positive business impact? Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, this is important. Hotels can offer non-refundable options or booking perks for guests who book directly to reduce cancellations. Also, they can focus more on direct bookings where they have better control and don't lose money to commissions.**

###**5.Solution To Business Objective**

What Do You Suggest The Client To Achieve Business Objective?

**Reduce OTA cancellations by offering perks for direct website bookings (e.g., discounts, loyalty points).**

**Focus marketing on peak months (July, August) and run discounts during low months (January, November).**

**Invest in marketing in top countries like Portugal, UK, and France with localized offers.**


**Offer more of Room Type A and upsell with smart pricing.**


**Create special weekend packages to boost short stays.**


**Bundle bed & breakfast, the most preferred option, to increase satisfaction and F&B revenue .**


**Most guests are solo or couple travelers—offer personalized deals.**


**OTAs have high cancellations—encourage non-refundable or prepaid options.**

**Launch early bird discounts for long lead times and last-minute deals to fill gaps.**


**City Hotels: Improve loyalty and services to retain demand.
Resort Hotels: Add experiences (spa, nature tours) to attract more bookings.**

### **Conclusion**

**1.City hotels experience more cancellations than resort hotels.**

**2.July and August are peak months; bookings drop in January and November.**

**3.Bookings increased from 2015 to 2017.**

**4.Bed & Breakfast (BB) is the most chosen meal plan.**

**5.City hotels get more bookings than resort hotels.**

**6.Room Type A is the most booked.**

**7.Portugal, UK, and France lead in bookings.**

**8.ADR varies by hotel and month; city hotels often have a higher ADR.**

**9.Most bookings are made 30 to 90 days in advance.**

**10.Transient (individual) customers dominate.**

**11.People stay longer during weekdays than weekends.**

**12.Online Travel Agents (OTAs) have the most cancellations.**

### ***Hurrah! You Have Successfully Completed Your EDA Capstone Project!!!***
"""